name: WorldOfZombies
version: ${project.version}
author: Mackblue
description: World of Zombies primary custom plugin
main: me.mackblue.worldofzombies.WorldOfZombies
website: https://github.com/Mackblue1/WorldOfZombies
api-version: 1.16
depend:
  - ProtocolLib
  - NBTAPI

commands:
  worldofzombies:
    description: Main plugin command which is used to run all sub-commands
    aliases: [woz]
    usage: "§cUsage: /woz [command] [args]"
    permission: worldofzombies.command.base
    permission-message: "§cYou do not have permission to run this command!"

permissions:
  worldofzombies.*:
    description: Includes all permissions for this plugin
    children:
      worldofzombies.command.*: true

  worldofzombies.command.*:
    description: Allows a player to run any of this plugin's commands
    children:
      worldofzombies.command.reload: true
      worldofzombies.command.info: true
      worldofzombies.command.database: true
      worldofzombies.command.get: true
      worldofzombies.command.item: true


  worldofzombies.command.base:
    description: Base permission which allows a player to use the base /woz command

  worldofzombies.command.reload:
    description: Reload this plugin's config files
    children:
      worldofzombies.command.base: true

  worldofzombies.command.info:
    description: Get information about this plugin
    children:
      worldofzombies.command.base: true

  worldofzombies.command.database:
    description: Delete or clone worlds' custom block databases
    children:
      worldofzombies.command.base: true

  worldofzombies.command.get:
    description: Get the "item" from a custom block's definition
    children:
      worldofzombies.command.base: true

  worldofzombies.command.item:
    description: Get the NBT API string for the held item
    children:
      worldofzombies.command.base: true